worker_processes auto;
error_log /var/log/nginx/error.log debug;
events { worker_connections 1024; }

rtmp {
  server {
    listen 1935;
    chunk_size 4096;
    notify_method get;

    application live {
      live on;
      hls on;
      hls_path /var/hls;
      hls_fragment 2s;
      hls_playlist_length 10s;
      hls_nested on;
      hls_cleanup on;

      exec_push /etc/nginx/transcode.sh $name;

      on_publish http://backend:8080/api/streams/on-publish;
      on_publish_done http://backend:8080/api/streams/on-publish-done;
      on_play http://backend:8080/api/streams/on-play;
    }
  }
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  server {
    listen 8088;

    location /hls {
      root /var;
      types {
        application/vnd.apple.mpegurl m3u8;
        video/mp2t ts;
      }
      add_header Cache-Control no-cache;
      add_header Access-Control-Allow-Origin *;
      add_header Access-Control-Allow-Headers *;
    }

    location /stat {
      rtmp_stat all;
      rtmp_stat_stylesheet stat.xsl;
    }
  }
}
